# Generated by Django 5.0.3 on 2024-03-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminarsapp', '0003_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='seminarsapp/'),
        ),
    ]
